### ISSUE TITLE
yarn dev 报错

### ISSUE THREAD

**Issue by tim0991** [cnu4/Webpack-Vue-MultiplePage#8]
```shell
yarn run v1.5.1
$ webpack-dev-server --inline --hot
{ 'another/index': './source/another/index/index.js',
  'index/index': './source/index/index/index.js',
  'index/info': './source/index/info/info.js' }
{ 'another/index': './source/another/index/index.html',
  'index/index': './source/index/index/index.html',
  'index/info': './source/index/info/info.html' }
events.js:112
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1353:14)
    at listenInCluster (net.js:1394:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1509:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:102:10)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c webpack-dev-server --inline --hot
Directory: /Users/HFY/www/test/js/Webpack-Vue-MultiplePage
Output:
".
```

**Comment by cnu4** [comment]
端口被占用了，换个端口号试试

在 package.json 中的启动脚本 `webpack-dev-server --inline --hot` 后加上 `--port 8088` 试试

**Comment by tim0991** [comment]
有效
